### ISSUE TITLE
[iOS] If a tap hides the keyboard, then the default action may be swallowed

### ISSUE THREAD

**Issue by MichaelRumpler** [rotorgames/Rg.Plugins.Popup#11]
I have a popup with an Entry and a Switch. When the user focusses the Entry, then the whole popup moves up on the iPad which is great.
When the text has been entered and I tap the Switch to change its state, then the keyboard hides, the popup moves back down, but the state of the Switch sometimes does not change. Due to the tap it should change from on to off or vice versa.

@rotorgames **Fix  in:**
- [x] - UWP, WP
- [x] - Android
- [ ] - iOS

**Comment by rotorgames** [comment]
@MichaelRumpler Hi friend. I try solved the problem. Thank you

**Comment by rotorgames** [comment]
@MichaelRumpler Hi. This problem only simulator or device also?

**Comment by MichaelRumpler** [comment]
@rotorgames Sorry, I answered right away, but it seems to be lost.

I only tried it on my iPad so far. Didn't try any emulators.
But on the iPad I see it more often than not.

**Comment by rotorgames** [comment]
@rotorgames **Fix  in:**
- [x] - UWP, WP
- [x] - Android
- [ ] - iOS

**Comment by angyy10** [comment]
hi, i also encounter this issue, both on simulator and device
my popup has an entry and button, when on screen keyboard is shown, pressing the button only hides the keyboard, but did not trigger the button click event, user need to tap the button again to trigger event

**Comment by rotorgames** [comment]
@angyy10 Hi. This is big problem. Maybe I fix it in v1.1.0

**Comment by kvertner** [comment]
@rotorgames
Love the plugin!  This issue with the click event being lost with the keyboard dismiss is killing me.  Any chance you are still looking into this issue?

**Comment by rotorgames** [comment]
@kvertner I will not fix it for 1.x.x version because 2.x.x version will change all structure and plugin will not have this problem. I hope you will wait new 2.x.x ;)

**Comment by kvertner** [comment]
@rotorgames Thanks for the prompt response.  

When do you think 2.x.x will be available?

**Comment by rotorgames** [comment]
@kvertner I have a busy schedule, I make three project and support several librarys. I'm not having time now. But I try to finish 2.0 until summer.

**Comment by ihassantariq** [comment]
I am able to fix this error. @rotorgames please remove this line from OnLayout method. So I can use your code instead of copy of your code.. 

protected override void OnLayout(bool changed, int l, int t, int r, int b)
		{
			//Element.ForceLayout(); //You have to remove this 
			base.OnLayout(changed, l, t, r, b);
		}
I was having this error on Android only. The file url of the Github is https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs 

If you remove this line. It will solve the error on android.  You can get the description of the error by reading the first comment of the @angyy10 
Thanks for the great plugin. 👍

**Comment by rotorgames** [comment]
@ihassantariq Thank you. I will test it.

**Comment by rotorgames** [comment]
@ihassantariq @kvertner @angyy10 @MichaelRumpler this issue was fixed in v1.1.0-pre. Please test it and tell me about your tests. Thank you.

**Comment by kvertner** [comment]
Thank you! I tested v1.1.0-pre two different apps in iOS 9.3.5 and it works perfect!


On Saturday, May 13, 2017, 11:58:29 AM PDT, Kirill <notifications@github.com> wrote:
@ihassantariq @kvertner @angyy10 @MichaelRumpler this issue was fixed in v1.1.0-pre. Please test it and tell me about your tests. Thank you.

**Comment by rotorgames** [comment]
@kvertner Nice to hear it :)
