### ISSUE TITLE
Popups not working on some Galaxy devices

### ISSUE THREAD

**Issue by Sebastian1989101** [rotorgames/Rg.Plugins.Popup#159]
On some galaxy devices (I got reports for S6, S7, S7 Edge) the Popups do not appear and/or are not closable with the Pop-Command. Sadly I have no specific logs because it does not happen on my development devices but on some of my users.

**Comment by Sebastian1989101** [comment]
Still waiting for a response / answer. Got more and more requests about this issue. Here is the screenshot of the issue (the pop is a "Map settings" dialog. The app is called "Breath Companion"): http://puu.sh/xrtdd/01777a5248.png

**Comment by NicolasGriere** [comment]
Hello, we ran into a similar problem when running our app on Samsung Galaxy Devices.
The problem didn't appear when pushing the popup to the screen but when we tried to remove it. 

Before we were using:
await Navigation.PopPopupAsync()
and 
await Navigation.PopAllPopupAsync()

**Getting rid of the animation fixed the issue for us:**
await Navigation.PopPopupAsync(**false**)
and 
await Navigation.PopAllPopupAsync(**false**)

I'm guessing the animation doesn't end properly on certain devices. In our case, we prefered getting rid of it than having the popup not removed at all..

PS: The Galaxy devices on which popups weren't working had just been updated to Android 7.0 ... Prior to that our app worked fine on them

**Comment by Sebastian1989101** [comment]
It really sucks that the developer of this plugin does completly ignore this bug... Is such a worse case that such a workaround is necessary...

**Comment by ValonK** [comment]
@Sebastian1989101  Why are you not fixing it yourself? The code is Open Source, there is this great Tool called Debugger. On my S8+, S8, Note8, S7 I have no problems at all.

**Comment by Sebastian1989101** [comment]
"Why are you not fixing it yourself?" - why are you not fix the poor Face unlocking on the S8? The required part of Android is open source. Maybe because I'm not the only one with the problem? Should everybody fix it by themself because you are to lazy? It's your repository and your library not ours. 

"On my S8+, S8, Note8, S7 I have no problems at all." - yea thats why nobody else had this problem especially on android... oh wait other have this problem  on exact this devices. I guess it might be conflicted with reduced animations configurations but I do not have the time to look up for this. 

It's a very very bad style from a developer to say "fix it yourself" if you are responsible for this library. Thats like OS manufacturers say: "Oh there is a security problem? Well here is the sourcecode, fix it yourself". You know your library better than anybody else. And as a provider of such a library it should be in your interest to fix such kind of issues. If I had a co worker with such a attitude it would be a obvious reason to fire him.

**Comment by opcodewriter** [comment]
@Sebastian1989101 You're not being fair here. I understand you're frustrated, as we all are from time to time, it's part of our job. But you have to understand this is OSS and it's free, the guy who created this library has been offering it for free. 

> I guess it might be conflicted with reduced animations configurations but I do not have the time to look up for this.

Well, if you don't have time why should the author have? Just because he shared his work, nobody forces you to use it.  The author not even Xamarin, a company owned  now by Microsoft giant, with developers hired for the job.
Why don't you try spend 5-8 hours in a weekend, try to debug it, and come up at least with some ideas if not a PR?

**Comment by Sebastian1989101** [comment]
@opcodewriter yes, I was a bit frustrated. But not so much that it don't work as expected more because the developer is in the opinion "I don't have the bug so fuck it". This type of "developer" is the reason why some software products are so much fucked up. If he had told me that he does not have the time for that or that he does not have an idea how this happens, I properly would try to fix it. But the author is more in the "Not my problem so I don't care"-Position and people like this should stop creating software because with this opinion you are only creating shitty software. 

Maybe I make myself looking very bad, but as you know too - if he works with the same attitude he would be get fired properly on 90% of all companies.

**Comment by opcodewriter** [comment]
Do you realize who the author is? He didn't even comment to this issue. Just because he didn't comment on it, doesn't mean all the statements you made are correct. You're putting words into this mouth.
How about spend some time yourself, find the issue or at least comment with something useful and this way contribute with something?

**Comment by erikpowa** [comment]
Popup will not work if you have disabled animations in Developer Options (or custom rom.....)... because the animations are never getting started, so just gets stuck. You have to implement a dependency service to check if the animation duration on the phone is disabled or "slowed down".
Have you ever tried pushpageasync(true) in xamarin with 0.0x animation speed on the phone?
Let's blame Xamarin together 💃 (just kidding)

**Comment by ValonK** [comment]
@Sebastian1989101  

>  This type of "developer" is the reason why some software products are so much fucked up. 

In fact, Copy & Pasting Code without using your brain to fix or figure out things introduces the most security flaws in Software ( People like you ). 
[https://www.heise.de/security/meldung/Studie-Android-Entwickler-kopieren-oft-auch-Sicherheitsluecken-3837076.html](url)

Instead of taking the time to bitch about the Developer or Me, you could have had time to fix the issue.
Here where I work we fix things ourselves.

**Comment by Sebastian1989101** [comment]
Great. You can quote from a site that does not even do any research and copy posts from other sites with a delay of days. Also I do not Copy & Paste code, I use a library that is provided here. 

I already mention what the problem might be. Every developer should fix things they create by themself and not request other todo so. In this case the library developer should fix it for a few reasons:

1. I'm not the only one who had this problem. If I fix it in my solution the problem is still there for anybody else. 
2. As developer of a framework, library or other kind of component you know you shit way better than others do. The required time to fix something is way less. 

If you had the time in your company to fix other issues all the time, it's fine.

**Comment by ValonK** [comment]
@Sebastian1989101  IM NOT THE DEVELOPER OF THIS LIBRARY !!!! 
You don't even know which library you are using! The developer is not required to fix anything, he shared his code for us to use.

**Comment by Sebastian1989101** [comment]
@ValonK yes I know. Guys like you are just here to cry and try to change other peoples mind because you are not able to accept other opinions. But go ahead if you like it. Maybe someday you will also create a working software and realize how important that is that experts, guys who creates someting, fix there stuff by themself and not require others to fix stuff.

**Comment by erikpowa** [comment]
By "animation" I meant
For.eg. in LineageOS (custom rom) in dev options there are
1. "Window animation scale"
2. "Transition animation scale"
3. "Animator duration scale"

Tip: There is always a persisted debug task for me before publishing (a new version of an app) where I have to go trough the app with these settings as turned off (Animation off)

@Sebastian1989101  The **PushPopupAsync** exposed the ability to able to set if you want animation. You should be glad. Xamarin (XF) foreg has no option (not sure if you can do that right now) to pop a page without animation from the "NavigationPage" when you press that back button/icon (not hardwarebutton)
(They have that NavigationProxy thing. You had / have to mess around there to get the ability without re-implementing the whole NavigationPage or creating a new viewrenderer for that on every platform) to achieve what you want.

You should open an issue here: https://bugzilla.xamarin.com/ with the animation problem.

🧀

**Comment by rotorgames** [comment]
@Sebastian1989101 Hi. Sorry for long answer. Please write android versions which have this problem or please notify me if you have fixed this problem. Thanks.

**Comment by Amenti** [comment]
I have the same/maybe similar problem but it is not specific to Galaxy devices. So far it happened for a small amount of users with Android 7 and 8. In my case the Push always works, the dialog can be interacted with but the Pop does nothing at all.

Sadly I can't reproduce it at all on my dev devices or in the simulator. It started to happen after we did upgrade to Xamarin.Forms 2.4 and started to use .Net Standard 2.0 so it's possible that the culprit lies elsewhere.

**Comment by rotorgames** [comment]
@Amenti This plugins uses a Xamarin.Forms animation to animate pages. If a xamarin forms animation has a bug then this plugin will not work.

**Comment by rotorgames** [comment]
I have fixed it in the beta release v1.1.3.121-beta. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

P.S. Not afraid to reopen this issue if you have this problem again.

Thanks
