### ISSUE TITLE
Support for .NET Standard 2.0

### ISSUE THREAD

**Issue by AlessandroDelSole** [rotorgames/Rg.Plugins.Popup#172]
As per the latest Xamarin.Forms stable release (2.4.0.280) which supports .NET Standard 2.0, it would be great if your library could support .NET Standard 2.0 directly.

Thanks.

**Comment by rotorgames** [comment]
@AlessandroDelSole Hi. I sure that this library will support .NET Standard 2.0 soon. But I can't say when exactly.

**Comment by ddobrev** [comment]
I vote for this too, especially since the latest version of Xamarin.Forms seems to no longer function with PCL.

**Comment by mackayn** [comment]
Forms 2.4.0 SR3 works okay with PCL Profile259 & Rg.Plugins.Popup (I built an app today for release). For the next release of Xamarin 15.3-pre they are doing away with the PCL templates.

https://twitter.com/pierceboggan/status/928039566161928192

**Comment by chadramsey** [comment]
+1 for this as well.

**Comment by rotorgames** [comment]
Thanks everyone. I will work on this.

**Comment by dansiegel** [comment]
@rotorgames feel free to ping me if you need any help on this.

**Comment by rotorgames** [comment]
@dansiegel Ok

**Comment by abrasat** [comment]
+1.
Is there any workaround available to reference the plugin from a NetStandard project ?
Does the NetStandard support mean the refactoring of the code, or is more related to adding the NetStandard target to the nuget package ?

**Comment by dansiegel** [comment]
@abrasat this is a little different depending on whether you are using a netstandard1.X project or netstandard2.0 project. You will need to update your csproj as shown below depending on the netstandard version you're using. Keep in mind that you will see a warning when you restore but everything will still work.

## 1.X

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wpa81+wp8</PackageTargetFallback>
  </PropertyGroup>
</Project>
```

## 2.0

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssetTargetFallback>$(PackageTargetFallback);portable-net45+win8+wpa81+wp8</AssetTargetFallback>
  </PropertyGroup>
</Project>
```

**Comment by dansiegel** [comment]
@rotorgames I was toying with this to see how challenging it would be to update, and as it turns out it was a pretty smooth update I can get you a PR if you like. Just a few notes on the branch I was working on:

1. Removes support for WinPhone since it has been officially removed from Xamarin Forms on GitHub
1. Add support for netstandard1.0 and netstandard2.0
1. Update to SDK Style allowing the project to multi-target and eliminate the need to manage 3 dlls in a single nuget.

I'm not sure if you have any CI process setup but with the new style project we can easily configure it to allow you to control CI versions based on build number and allow you to still set the version you want in all other cases. Also I'm assuming you want this based on your v1.1.0 branch.

**Comment by abrasat** [comment]
@dansiegel Thx. Could install and compile the Rg.Plugins.Popup plugin nuget package in a netstandard 2.0 library. Got it working in a UWP project that references the netstandard class library. Have problems getting it working on android, as the Rg.Plugins.Popup nuget package has to be installed also in the android project due to Xamarin.Forms bug ( [https://bugzilla.xamarin.com/show_bug.cgi?id=59313](https://bugzilla.xamarin.com/show_bug.cgi?id=59313) )
Guess the best solution would be a "clean" netstandard 2.0 compatible Rg.Plugins.Popup nuget package.

**Comment by rotorgames** [comment]
Hi there. NET.Standart 2.0 will be supported in v1.1.0-pre6

**Comment by aleksandrsmyk** [comment]
@rotorgames Will you plan to update stable nugget package for .NetStandart support too?

**Comment by rotorgames** [comment]
@aleksandrsmyk Yes I will but it will not be soon because I didn't to do some things that I wanted. 

P.S. v1.1.0-pre9 is more stable than 1.0.4. You should not be afraid pre releases.

**Comment by abrasat** [comment]
Is there a v1.1.0-pre9 version available ? On nuget.org v1.1.0-pre8 is the newest version.

**Comment by rotorgames** [comment]
@abrasat I don't understand why v1.1.0-pre9 is in Validating status in nuget more than 3 hours. You can use v1.1.0-pre8. These packages have different only a Xamarin.Forms minimum version.

**Comment by aleksandrsmyk** [comment]
@rotorgames Will you plan to publish release version with .NET Standard 2.0 support?

**Comment by rotorgames** [comment]
@aleksandrsmyk The last pre release supports .NET Standard 2.0
