### ISSUE TITLE
Custom TabbedPage

### ISSUE THREAD

**Issue by vitormcs** [rotorgames/Rg.Plugins.Popup#198]
I have a custom renderer in my tabbedPage, since I could not use this plugin. Right ?

**Comment by rotorgames** [comment]
@vitormcs You can use this plugin for all xamarin forms pages.

**Comment by EmilAlipiev** [comment]
@rotorgames  just a quick suggestion, my friend. you should close the tickets if owner doesn't provide enough information and doesnt return back within 1-2 weeks. otherwise it looks many open issues and for the first users it looks like plugin has problem. for example, i always check how many open issues there are before I start a new plugin. if owner of issue has still problem, he can comment and issue can be reopened. dont so kind :) thank you.
