### ISSUE TITLE
PopupRenderer throwing ClassNotFoundException

### ISSUE THREAD

**Issue by KaizerT** [rotorgames/Rg.Plugins.Popup#291]
It doesn't seem like calling Popup.Init() initializes the popup renderer in the dex. Upon trying to call popup navigation functions the compiler throws a ClassNotFoundException. Looking at the source code the LinkAssemblies function does not seem to be triggered since the condition is if (false.Equals(true))

**Comment by rotorgames** [comment]
@KaizerT Hi. It can happen because you use Multidex in your project, I think it happens only on Android <= 5.0.2 when multidex is enable. You can get more information [here](https://www.jon-douglas.com/2016/09/23/xamarin-android-multidex-keep/). Also `if (false.Equals(true))` is in the plugin only for the xamarin linker, this code must not be invoked in runtime.
