### ISSUE TITLE
Crashing on Android (Soft Keyboard open while closing)

### ISSUE THREAD

**Issue by nitrouscutter** [rotorgames/Rg.Plugins.Popup#311]
When opening a Rg pop up with an input field. If you tap the input field to open the soft keyboard, then tap close on the modal (PopupNavigation.Instance.PopAsync(false)), the library crashes the app.

**Comment by nitrouscutter** [comment]
Version 1.1.4.145-pre

**Comment by MDemetrio** [comment]
Hi, i'm also facing this issue, here's my stacktrace:
```
Xamarin Exception Stack:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <db2018083aad4fe8b75b4ca130adc94b>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <db2018083aad4fe8b75b4ca130adc94b>:0
  at Android.Views.View.get_Context () [0x0000a] in <da77256d21d540ab98586180f7387bd6>:0
  at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <182db72c19df4b0082953f04c7e0f2a0>:0
  at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <da77256d21d540ab98586180f7387bd6>:0
  at (wrapper dynamic-method) System.Object.645aceb3-7e9e-4d23-a42c-2b297ffa81c9(intptr,intptr,intptr)
```

**Comment by fedec93** [comment]
Same thing happening on iOS 11.x

When you open a popup, click on an input field, the keyboard opens. If you then close the popup, the app crashes

**Comment by JKennedy24** [comment]
looks like same issue as https://github.com/rotorgames/Rg.Plugins.Popup/issues/157

**Comment by ClintTCG** [comment]
Same thing happening for us on Samsung Android devices.

We were able to get around this by wrapping all of our calls to PopupNavigation.Instance in `Device.BeginInvokeOnMainThread()` calls.  

I suspect that a "real" fix might involve something with `PopupNavigationImpl.cs` and wrapping the guts of `AddAsync`, `RemoveAsync`, and `RemovePopupFromStack` with a `Device.BeginInvokeOnMainThread()` check.  

This might also require the addition of a TaskCompletionSource so that instead of having random Task.Delay(50) calls in that file, it's able to wait until the main thread is able to modify the display stack and complete the task for everyone awaiting on it.

**Comment by rotorgames** [comment]
@ClintTCG I tested this plugin on a lot of android devices and emulators and it was ok. Can you tell me android version and device name that I will be able to reproduce it?

**Comment by ibonsanvicente** [comment]
I have the same issue with versions 1.1.4.168 & 1.1.5.180.

I'm testing with a Samsung Galaxy S8+, Android 8.0.0.

In my case I have picker & entry controls in the popup page. If the soft keyboard is displayed because having inserted some text in the entry control, upon closure, the picker's selection window is displayed (it is the first element in the popup). If the user selects any item then the app crashes because the element exists no more.

In my case this solution did not work:

            Device.BeginInvokeOnMainThread(async () =>
            {
                await PopupNavigation.Instance.PopAsync(false);
            });

If you need any more information regarding the code I'm using or versions lease let me know.

In the meanwhile I'll try to workaround setting up some code to force closure of soft keyboard on Android right before calling to Popup Close. Hope it'll do the trick.

btw, thanks for your work!

**Comment by ibonsanvicente** [comment]
[App4.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/2686515/App4.zip)

I've created a very simple quick repro project.

Main page displays a button to launch a popup page.

As in my example above there is a picker as first element, an entry as second and 2 buttons. One of those does absolutely nothing and the other closes the popup.

If the soft keyboard is displayed, upon clicking any of the buttons the picker window will be displayed.

**Comment by rotorgames** [comment]
About `Cannot access a disposed object`: 
I hope that I fixed it in the last version of the plugin which is available in [the development nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup) right now. All navigation is invoked in the main thread in the last release whatever how navigation has been invoked in the user's code.

I will be happy if someone can test it with the last version of the plugin >= 1.1.5.184.

Thanks.

About picker:
I fixed it also. I removed `RequestFocus` but it is not problem of the plugin.
