### ISSUE TITLE
How to close the top-most popup?

### ISSUE THREAD

**Issue by primehalo** [rotorgames/Rg.Plugins.Popup#326]
How do I close the top-most popup? If I call `Navigation.PushPopupAsync(MySecondPopup)` then in that second popup use `Navigation.PopAsync()`, nothing happens. I can use `Navigation.PopAllPopupAsync()` to close all the popups but I only want to close the top-most one.

**Comment by pfaucon** [comment]
navigation.popasync probably uses the XF normal pop.  You need to use the one where you pass the cardpage (RemovePopupPageAsync).  I'm using the code below so that a pop-up can close itself (or rather a generic content view hosted inside of an adapter page can close itself)

protected void DismissCardPage()
		{
			Device.BeginInvokeOnMainThread(() =>
		  {
			  Navigation.RemovePopupPageAsync(GetParentPopupPage());
		  });
		}

		protected PopupPage GetParentPopupPage()
		{
			var par = this.Parent;
			while (!(par is PopupPage) && par.Parent != null)
			{
				par = par.Parent;
			}
			if (par is PopupPage)
			{
				return (PopupPage)par;
			}
			return null;
		}

**Comment by rotorgames** [comment]
Read [the documentation of navigation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Navigation).
