### ISSUE TITLE
Add this to troubleshooting

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [rotorgames/Rg.Plugins.Popup#332]
If you get this error below, when Init app, or your splash screen infinity loading and nothing happens, then delete **obj** and **bin** folders from your projects/

System.TypeLoadException: Could not resolve type with token 01000066 (from typeref, class/assembly Rg.Plugins.Popup.Popup, Rg.Plugins.Popup.Droid, Version=1.1.4.145, Culture=neutral, PublicKeyToken=null)

**Comment by EmilAlipiev** [comment]
this has nothing to do with this library. this is general xamarin forms problem with nuget caching. such type of errors occurs also with other nuget packages in xamarin forms and non-beginner should already know that he should always clearn bin and obj files and rebuild solution in such cases. if you feel, it is related to this library, please provide a PR instead of expecting owner to do this.
