### ISSUE TITLE
[iOS] Showing camera from a PopupPage does not allow returning to PopupPage

### ISSUE THREAD

**Issue by dfarrNTST** [rotorgames/Rg.Plugins.Popup#334]
We have a requirement to take a picture from a PopupPage...on Android this works as needed where after taking the picture we are returned to the PopupPage.  On iOS, this does not happen...it returns to the owner/parent of the PopupPage.  How do we resolve this so it works the same as it does on Android?

I have attached a sample solution that demonstrates this discrepancy.

Thanks!

[Popup Camera Issue - Xam.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/2145821/Popup.Camera.Issue.-.Xam.zip)

**Comment by ClintTCG** [comment]
Running into this same issue.  @dfarrNTST Would be curious to know if you found anything!

**Comment by ClintTCG** [comment]
@dfarrNTST 
I found a fix.  This looks like it might more be an issue with the image chooser library you're using. When creating your image picker popup, make sure that you set the `ModalPresentationStyle` to `UIModalPresentationStyle.OverCurrentContext;`.  

I'm not super familiar with MediaPlugin, but it looks like there's a way to pass in options so that you can set the modal presentation style to `OverCurrentContext` like you need:
https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin/iOS/MediaImplementation.cs#L96

**Comment by dfarrNTST** [comment]
@ClintTCG This fixed it for us!  Thank you!!
