### ISSUE TITLE
Crashes on iOS when showing popup

### ISSUE THREAD

**Issue by anthonycklim** [rotorgames/Rg.Plugins.Popup#355]
iOS app crashes with the following exception. Using version 1.1.4.168 with Xamarin.Forms 2.5.0.280555

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Application tried to present modally an active controller <RgPopupPlatformRenderer: 0x1202e1a90>.
Native stack trace:
	0   CoreFoundation                      0x0000000183e22da4 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000182fdc5ec objc_exception_throw + 56
	2   UIKit                               0x000000018dc66ac8 <redacted> + 4812
	3   UIKit                               0x000000018dedf4b0 <redacted> + 68
	4   UIKit                               0x000000018d9f6148 <redacted> + 104
	5   UIKit                               0x000000018dedf40c <redacted> + 212
	6   UIKit                               0x000000018dc1d3e4 <redacted> + 512
	7   UIKit                               0x000000018dc657bc <redacted> + 180
	8   UIKit                               0x000000018dc65654 <redacted> + 160

**Comment by rotorgames** [comment]
@anthonycklim Can you give me more information about it? Can you create a simple project which reproduces this issue and upload it on GitHub for me?

**Comment by nick5454** [comment]
@rotorgames I am noticing a crash on the Simulator iOS 8 Plus 12.2. i'll create a project and post it. I also notice that I am trying to pop up your screen to hide switching the MainPage, you your tool doesn't show. I assume this is because i'm switching Navigation and your tool can't switch that.

**Comment by badavid85** [comment]
Same error for me on Xamarin.Forms 3.6.0.34447 and Rg.Plugins.Popup 1.1.5.188:
_Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException Application tried to present modally an active controller <RgPopupPlatformRenderer: 0x116005f50>._

In my case I show a Loading popup every time a user scans an RFID tag, which could happen multiple times in short period of time.

All I do is to make this call:
`await PopupNavigation.Instance.PushAsync(_loadingPopup);`

**Comment by bonmacalindong** [comment]
Any updates on this issue? Having the same problem in Rg.Plugins.Popup 1.1.5.188 and XF 3.5.0.169047

**Comment by nick5454** [comment]
My issue was because I was switching the main page, which is my fault.

You should upload a sample project to show your issue. There isn’t enough code to look at it. From first glance, I would say that you didn’t hide the pop up before you show it again. Which would explain the error “you are trying to show a view controller that already exists”

**Comment by nick5454** [comment]
You could also view your modal and navigation stack.

**Comment by rotorgames** [comment]
I think it happens because there are some popups on the screen, then you change a `MainPage` and after it, you try to do something with popups but it's wrong. It's because of all popup pages have `MainPage` as Parent. I'm going to change Parent of all opened popup pages if `MainPage` has been changed. I just have added it to the roadmap. 

Thanks, guys.
