### ISSUE TITLE
Talk back Accessibility focus moves to background controls for the left swipe on  pop up.

### ISSUE THREAD

**Issue by Srikanth540-L** [rotorgames/Rg.Plugins.Popup#497]
For Rg pop up we can  even access the background controls of page on which pop up as some,expected the focus should not move to background controls and should stay on the pop up it self.

**Comment by jfjalburquerque** [comment]
My problem is related to this one:

**Problem:** 
When I raise a popup the focus is setted to the background control, and I can press buttons from the background page.

**How to reproduce it:**
[UWP platform]
* If I press a button which raise a popup, popup is displayed.
* If I press space or enter key, the button that is pressed is a button from the background page instead of focussed button on popup (the button is setted to focus).

Thanks and good job !

**Comment by Srikanth540-L** [comment]
@rotorgames  Any update or ETA for this bug , Please suggest any solution if there is any.

**Comment by HeitorPaino** [comment]
I have the same problem using talkback. When i raise the popup, talkback still reads and interacts with the background elements. @rotorgames, is there any ETA or workaround for this bug?

**Comment by ponnumittathani** [comment]
@rotorgames  Any updates on this issue. Is there any alternative that can be tried to resolve this issue?

**Comment by LuckyDucko** [comment]
@ponnumittathani is your issue related to UWP or Android?

For Android, I recently made some changes detailed [here](https://github.com/rotorgames/Rg.Plugins.Popup/issues/585). We haven't released this to the current NuGet, however, I have added a video showing how to get the latest code working with your project

**Comment by ponnumittathani** [comment]
@LuckyDucko  Issue is in Android(Xamarin Forms)

**Comment by LuckyDucko** [comment]
@ponnumittathani I recommend trying out what I linked for Android then, see the bottom of the issue, and remember to add in  `AndroidTalkbackAccessibilityWorkaround` to true
