### ISSUE TITLE
Click background overlay to close popup

### ISSUE THREAD

**Issue by JoshuaNovak919** [rotorgames/Rg.Plugins.Popup#5]
Is there a way to make it so when you click the background overlay the popup will close? If not, it may be something good to add an option for. Excellent plugin btw :)

**Comment by rotorgames** [comment]
@JoshuaNovak919 Hi friend. Thank you for your interest in my plugin. 

Yes, I was planning to make the closing Popup by clicking on the background. It is already in my Todo list. I will try to add this feature in the new version. I also try to add blur the background, for Android and iOS.

**Comment by JoshuaNovak919** [comment]
@rotorgames Awesome!! Those were things I was thinking about too! I love how easy it is to make custom animations for your plugin too btw. It's very well thought out.

**Comment by rotorgames** [comment]
@JoshuaNovak919 Glad to hear it. As soon as news, background click and background blur, I will write here. Thank you.

**Comment by rotorgames** [comment]
@JoshuaNovak919 Hi friend. I'm add closing popup when background click. 

I also did some experiments with blurred background.

On of iOS, it turned out to make a blurry background, but it looks very bad, and the ugly.
On Android, this is not a trivial task. It is difficult and takes too much time.

I decided to abandon the idea until a blurry background.

But you can always expand and `PopupPage`` PopupPageRenderer` custom renderers.

All changes are already available in version 0.0.10.

Thank you.
