### ISSUE TITLE
Cannot Init Plugin

### ISSUE THREAD

**Issue by ghost** [rotorgames/Rg.Plugins.Popup#554]
Dear all,

i wanted to include the Plugin into my Xamarin Forms App.
Unfortunately I cannot init it with the following command:

Rg.Plugins.Popup.Popup.Init();
Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Popup.GetExtraAssemblies());

It seems that "Popup" is not available.

![image](https://user-images.githubusercontent.com/60783656/86394186-73b02600-bc9e-11ea-9b70-c202db48dba5.png)

I am using the following setup:

Rg.Plugins.Popup Version 2.0.0.3
Xamarin.Forms Version 4.6.0.726

Thanks for your help,

Thomas

**Comment by Brosten** [comment]
Seems to be a bug in latest (2.x) version of the plugin. I get the same issue

**Comment by martijn00** [comment]
Look at all the closed issues. It's not a bug, you just need to read the readme more careful.

**Comment by Brosten** [comment]
Ok, so the problem was the min target version of Windows projekt. I still think it could be made readme that this is a demand for using 2.x. 
There is also a diff between "Getting started" and "Troubleshooting". In trouble, this line is commented out
Rg.Plugins.Popup.Popup.Init();
Should it be there or not?
