### ISSUE TITLE
Support hot reaload 

### ISSUE THREAD

**Issue by softlion** [rotorgames/Rg.Plugins.Popup#572]
## 🚀 Feature Requests

When a xaml is opened using Rg.Plugin.Popup, and the xaml content is changed while debugging, xamarin hot reaload does not work: no change appear on the device screen.

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@softlion can you make a PR?

**Comment by softlion** [comment]
Well i don't know where to start. Maybe you can guide ?

**Comment by martijn00** [comment]
Hmm, I have no idea at the moment. Maybe you can look at other libs that do support it and see what is different?

**Comment by softlion** [comment]
I don’t know of any of those libs

**Comment by LuckyDucko** [comment]
@martijn00 
I was under the impression that Hot reload has always worked, perhaps there is something specific in softlions setup

![Example](https://j.gifs.com/4QZJBV.gif)

**Comment by scriptBoris** [comment]
Hot reload still not working 
- Android
- iOS
- VisualStudio Community 2022

**Comment by danieldefreitasleite** [comment]
I can confirm that it is not working and try to edit it without hot reload is a pain because everyone knows how long it takes to build and deploy any small change...

**Comment by mhrastegari** [comment]
@danieldefreitasleite yeah :(

**Comment by BaltoAF** [comment]
Still doesn't work en Visual Studio 2022 v17.1.0 + Android/iOS.

A workaround to use HotReload is to show the popup as a classic page :
`await Shell.Current.Navigation.PushAsync(new MyPopupPage())`
instead of 
`await PopupNavigation.Instance.PushAsync(new MyPopupPage())`

The page appears broken (without transparency, embedded in a navigation page in my case), but hot reload is active, so you can fix the main display problems, while creating your page. Revert to PopupNavigation.Instance.PushAsync when all is OK.
