### ISSUE TITLE
How to popup page in Detail page in MDP?

### ISSUE THREAD

**Issue by Codespilot** [rotorgames/Rg.Plugins.Popup#598]
## 💬 Questions and Help

I use Xamarin.Forms MasterDetailPage in iPad landscape mode. When I popup a page, it always covers fullscreen, so is there any way to popup it just in specified area, like Master page or Detail page?

Sample:

![image](https://user-images.githubusercontent.com/10270723/99751071-74960700-2b1c-11eb-9939-c0d502657c9b.png)

**Comment by LuckyDucko** [comment]
@realzhaorong 

To do this, I suggest using absoluteLayout on your popuppage to force it to a certain area, using proportional scaling so it works on iPad devices.

(You may also need to check Device.Idiom so that iPhones will just open the popup like normal)

I assume you still want some form of interactivity in the 'Master' section, to help with that, PopupPages have the ability to 'Pass' touch events to the pages behind them. To do this you need the following settings on your PopupPage

**BackgroundInputTransparent - true** if a background of PopupPage should receive input and should, instead, pass inputs to the elements that are visually behind the current visual element. Works only on Android and iOS at the moment.

and you need to ensure that your pouppage does not have FillAndExpand or fill, as mentioned in the following page
https://github.com/rotorgames/Rg.Plugins.Popup/wiki/PopupPage which I recommend you read through just to be safe.

This should allow you to work with the master section of your screen, with the popup, using some absoluteLayout magic, can be set to just exist within the detail part.
