### ISSUE TITLE
PushAsync doesn't work in landscape mode

### ISSUE THREAD

**Issue by fhintsch** [rotorgames/Rg.Plugins.Popup#602]
## 🔙 Regression

Calling _PopupNavigation.Instance.PushAsync_ while in landscape mode will result in a 'frozen' screen and the popup won't be shown. If you rotate the device (iPhone XR) to portrait, the popup is shown and everything works fine.

### Old (and correct) behavior

In version 2.0.0.6 it was okay.

### Current behavior

In version 2.0.0.7 it is broken.

### Reproduction steps

Call _PopupNavigation.Instance.PushAsync_ while in landscape mode.

### Configuration

**Version:** 2.0.0.7
Xamarin.Forms: 4.8.0.1687

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@fhintsch good catch, I reproduced this in the test project.

it seems that this is due to my recent change to make compatible with the latest pre-release of Xamarin.Forms, specifically this check (in Platforms->iOS->Extensions->PlatformExtensions->line 68)

```csharp
if (currentElement.SystemPadding != systemPadding 
```

Checking it again and testing it with the latest pre-release, removing this check seems to fix your described issue, and it _seems_ to not produce the behaviour it was intended to fix. I must've added it in there as a safeguard.

I'll create a quick PR that should remove this issue, cheers for bringing it up.
