### ISSUE TITLE
Keyboard offset not working with Version 2.0.0.7 or newer

### ISSUE THREAD

**Issue by WorldOfBasti** [rotorgames/Rg.Plugins.Popup#625]
### Expected behavior
Keyboard offset should work and resize the page with the padding height of keyboard

### Reproduction steps
1. Set HasKeyboardOffset to true
2. Add Entry, Picker or something similar to the page
3. Focus it and the bug will occur

### Configuration
**Version of Xamarin:** 4.8.0.1821 (latest stable release)
**Version of the plugin:** 2.0.0.7 or newer

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF (not testet)
- [ ] :earth_americas: UWP (not testet)
- [ ] :apple: MacOS (not testet)
- [ ] :tv: tvOS (not testet)
- [x] :monkey: Xamarin.Forms

### Sample:
[TestApp - Popup Issue Sample.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/5719774/TestApp.-.Popup.Issue.Sample.zip)

**Comment by WorldOfBasti** [comment]
Is there any progress or a solution? 2.0.0.6 isn't compatible with Xamarin.Forms 5+ and popups are important for us..

We could determine that if you remove the if statement in [line 64 in the PlatformExtension.cs file](https://github.com/rotorgames/Rg.Plugins.Popup/blob/d6e42adae2e957c1548ef5e6decfe3fa69abb6c6/Rg.Plugins.Popup/Platforms/Ios/Extensions/PlatformExtension.cs#L64) it will work as expected. Maybe this will help to fix this issue.

**Comment by LuckyDucko** [comment]
hey @WorldOfBasti I think I found it.

Line 64 was added in to make XF 5.0 work (a pre-release of it anyway), so while removing it does make XF4.8 work smooth, it does suffer the same original bug as #589. So I had to keep it in.

the fix was related however (good catch), adding an extra condition for the system padding changing, which is what the keyboard offset works with, allowed it to work. Line 64 is now

```csharp
  if ((renderer.Element.Width != superviewFrame.Width && renderer.Element.Height != superviewFrame.Height)
      || currentElement.SystemPadding.Bottom != systemPadding.Bottom)
  {
```

I have a branch `patch-#625`, do you mind giving it a whirl in your project and see if it helps out? if it does I'll merge it in

**Comment by WorldOfBasti** [comment]
Hello @LuckyDucko,
Yes I can confirm with this works it as expected.

**Comment by RadoslawKubas** [comment]
Hello, when is the new version with this fix expected to be available on NuGet?

**Comment by LuckyDucko** [comment]
only @martijn00 has control concerning the NuGets, I'll close this ticket when he pushes one out

**Comment by martijn00** [comment]
New nuget is up now
