### ISSUE TITLE
Label in collection view is not visualized

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#640]
## 🐛 Bug Report
[TestFody.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/5918501/TestFody.zip)

I have a Popup with a collectionview and a Label. There are 4 items in the CollectionView. Labels' text is invisible.

![image](https://user-images.githubusercontent.com/5759350/106748883-24601880-6626-11eb-9c6a-947ed8792327.png)

If I change the xml and execute HotReload, the Text become visible

![image](https://user-images.githubusercontent.com/5759350/106748943-3a6dd900-6626-11eb-91e4-9c95da0b2665.png)

### Expected behavior
Text should be visible

### Reproduction steps
Take a look to zip. Press the first button that visualize the popup

### Configuration

**Version:** 2.0.0.10

**Platform:** 
- [ ] :iphone: iOS
- [ X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
Hi @acaliaro 

After a bit of poking around, I found out the error is not with rg, but the bindings in your data template.

The binding are correct, however, if I switch them from Classic bindings to [Compiled bindings](https://docs.microsoft.com/en-au/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings?WT.mc_id=compiledbindings-xamarinblog-jamont#use-compiled-bindings-in-a-datatemplate), everything works out.

XML
```
<CollectionView.ItemTemplate>
  <DataTemplate x:DataType="x:String">
  <StackLayout Padding="0,5" Style="{StaticResource CollectionViewStackLayoutStyle}">
  
	  <Label Style="{StaticResource CollectionViewLabelStyle}" Text="{Binding .}" />
  
  </StackLayout>
  </DataTemplate>
</CollectionView.ItemTemplate>
```

that **x:DataType="x:String"** is what makes this a compiled binding, along with xaml compilation and whatnot.

My guess is that since compiled binding are resolved much faster, there must be some issue with popup pages and their initial render cycle? perhaps during a certain timeframe it isn't able to properly resolve Property changes while its doing setup? it's all wild speculation at this point. 

let me know how this little fix goes, if it works out, feel free to close. this will be a good issue to reference in the future if we get any issues.

**Comment by acaliaro** [comment]
Excellent @LuckyDucko . Problem solved! Have a nice day
