### ISSUE TITLE
Get compatibility with MvvmCross

### ISSUE THREAD

**Issue by tnassour** [rotorgames/Rg.Plugins.Popup#647]
### Contextualize the feature

Actually this plug in is not compatible with MvvmCross how is it possible to display these dialogs with MvvmCross

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [x ] :robot: Android
- [ x] :checkered_flag: WPF
- [ x] :earth_americas: UWP
- [ x] :apple: MacOS
- [ x] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
hey @tnassour to achieve compatibility, there would need to be a seperate package, similar to prism being compatible through @dansiegel [helpful contributions](https://github.com/dansiegel/Prism.Plugin.Popups)

Perhaps you can talk to some Mvvmcross developers to maybe create a similar thin wrapper? 

Otherwise, I'm going to close this issue as its outside of the scope of this plugin
